from typing import List, Tuple

import arabic_reshaper
from bidi.algorithm import get_display
from PIL import ImageFont, ImageDraw


def shape_urdu(text: str) -> str:
    if not text:
        return ""
    reshaped = arabic_reshaper.reshape(text)
    bidi_text = get_display(reshaped)
    return bidi_text


def wrap_text_rtl(
    text: str,
    font: ImageFont.FreeTypeFont,
    max_width: int,
    draw: ImageDraw.ImageDraw,
) -> List[str]:
    # 1. Wrap logical text first (simple space splitting)
    # This avoids breaking the visual order generated by bidi algorithm later
    words = text.split(" ")
    lines: List[str] = []
    current_line_words: List[str] = []
    
    for word in words:
        # Test with current word added
        trial_words = current_line_words + [word]
        # Join, then shape to test width
        trial_text = " ".join(trial_words)
        shaped_trial = shape_urdu(trial_text)
        
        bbox = draw.textbbox((0, 0), shaped_trial, font=font)
        w = bbox[2] - bbox[0]
        
        if w <= max_width:
            current_line_words.append(word)
        else:
            if current_line_words:
                # Shape the completed line and add to lines
                full_line_text = " ".join(current_line_words)
                lines.append(shape_urdu(full_line_text))
                current_line_words = [word]
            else:
                # Word itself is too long, just add it (or split char by char if really needed)
                current_line_words = [word]
                
    if current_line_words:
        full_line_text = " ".join(current_line_words)
        lines.append(shape_urdu(full_line_text))
        
    return lines


def wrap_text_ltr(
    text: str,
    font: ImageFont.FreeTypeFont,
    max_width: int,
    draw: ImageDraw.ImageDraw,
) -> List[str]:
    words = text.split(" ")
    lines: List[str] = []
    current = ""
    for word in words:
        trial = (current + " " + word).strip()
        bbox = draw.textbbox((0, 0), trial, font=font)
        w = bbox[2] - bbox[0]
        if w <= max_width:
            current = trial
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines


def measure_multiline(
    lines: List[str], font: ImageFont.FreeTypeFont, line_spacing: int, draw: ImageDraw.ImageDraw
) -> Tuple[int, int]:
    widths = []
    total_height = 0
    for line in lines:
        bbox = draw.textbbox((0, 0), line, font=font)
        w = bbox[2] - bbox[0]
        h = bbox[3] - bbox[1]
        widths.append(w)
        total_height += h + line_spacing
    if widths:
        total_height -= line_spacing
    return (max(widths) if widths else 0, total_height)
